#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_IMAGE="$SCRIPT_DIR/resources/environments/default_environment.hdr"
OUT_HEADER="$SCRIPT_DIR/src/environments/default_environment.h"

# ---------------------------------------------------------------------------
# Embed resources/environments/default_environment.hdr as a byte array header.
#
# Source: "Cannon Exterior" by Greg Zaal — the Khronos glTF-Sample-Viewer's
# own default environment (KhronosGroup/glTF-Sample-Environments, path
# Cannon_Exterior.hdr on the low_resolution_hdrs branch; see that repo's
# Cannon_Exterior.hdr.license). Deliberately matches the reference viewer's
# default so campello_renderer's out-of-the-box look and IBL brightness are
# directly comparable to it, instead of the previous "Kiara 5 Noon" sky/sun
# HDRI (much higher dynamic range/more directional light — a fundamentally
# different, harsher lighting scenario, not just a different exposure).
# License: CC0 1.0 (public domain, no attribution required).
# 1024x512 equirectangular Radiance HDR — real (non-tonemapped) linear
# radiance data, so reflective/metallic materials still get real specular
# response rather than being capped by an LDR source image.
# ---------------------------------------------------------------------------
python3 - "$SRC_IMAGE" "$OUT_HEADER" <<'PYEOF'
import sys

def to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

src_path, out_path = sys.argv[1], sys.argv[2]
hex_data, size = to_hex_lines(src_path)

header = f"""#pragma once

// Auto-generated by build_default_environment.sh — do not edit.
// Rebuild with: ./build_default_environment.sh
//
// Embedded source: resources/environments/default_environment.hdr
// "Cannon Exterior" by Greg Zaal — the Khronos glTF-Sample-Viewer's own
// default environment (KhronosGroup/glTF-Sample-Environments), CC0 1.0.
// 1024x512 equirectangular Radiance HDR ({size} bytes) — real linear
// radiance data, used as the built-in default IBL environment map when the
// caller hasn't set one.

namespace systems::leal::campello_renderer::environments {{

static const unsigned char kDefaultEnvironmentHdr[] = {{
{hex_data}
}};
static const unsigned int kDefaultEnvironmentHdrSize = {size};

}} // namespace systems::leal::campello_renderer::environments
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}  ({size} bytes embedded)")
PYEOF
