#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders/vulkan"
OUT_HEADER="$SCRIPT_DIR/src/shaders/vulkan_default.h"

# ---------------------------------------------------------------------------
# Locate glslc — prefer NDK bundled version, fall back to PATH.
# ---------------------------------------------------------------------------
if [ -n "$ANDROID_NDK" ]; then
    case "$(uname -s)" in
        Darwin) GLSLC="$ANDROID_NDK/shader-tools/darwin-x86_64/glslc" ;;
        Linux)  GLSLC="$ANDROID_NDK/shader-tools/linux-x86_64/glslc"  ;;
        *)      GLSLC="glslc" ;;
    esac
else
    GLSLC="glslc"
fi

if ! command -v "$GLSLC" &>/dev/null && [ ! -x "$GLSLC" ]; then
    echo "Error: glslc not found. Set ANDROID_NDK or ensure glslc is in PATH."
    exit 1
fi

echo "Using glslc: $GLSLC"

# ---------------------------------------------------------------------------
# Compile GLSL → SPIR-V
# ---------------------------------------------------------------------------
"$GLSLC" "$SHADER_DIR/default.vert" -o "$SHADER_DIR/default_vert.spv"
echo "Compiled: default.vert → default_vert.spv"

"$GLSLC" "$SHADER_DIR/default.frag" -o "$SHADER_DIR/default_frag.spv"
echo "Compiled: default.frag → default_frag.spv"

"$GLSLC" "$SHADER_DIR/fxaa.vert" -o "$SHADER_DIR/fxaa_vert.spv"
echo "Compiled: fxaa.vert → fxaa_vert.spv"

"$GLSLC" "$SHADER_DIR/fxaa.frag" -o "$SHADER_DIR/fxaa_frag.spv"
echo "Compiled: fxaa.frag → fxaa_frag.spv"

"$GLSLC" "$SHADER_DIR/downsample.frag" -o "$SHADER_DIR/downsample_frag.spv"
echo "Compiled: downsample.frag → downsample_frag.spv"

# ---------------------------------------------------------------------------
# Helper: convert a .spv binary into a C hex byte array (12 bytes per line).
# ---------------------------------------------------------------------------
spv_to_c_array() {
    local file="$1"
    local size
    size=$(wc -c < "$file")
    local col=0
    local first=1
    local line=""

    while IFS= read -r -d '' -n 1 byte || [ -n "$byte" ]; do
        printf -v hex "0x%02x" "'$byte"
        if [ $first -eq 0 ]; then
            printf ", "
            if [ $col -eq 0 ]; then printf "\n    "; fi
        else
            printf "    "
            first=0
        fi
        printf "%s" "$hex"
        col=$(( (col + 1) % 12 ))
    done < "$file"
    printf "\n"
    echo "$size"
}

# ---------------------------------------------------------------------------
# Generate the header using Python (available on all host platforms).
# ---------------------------------------------------------------------------
python3 - "$SHADER_DIR/default_vert.spv" "$SHADER_DIR/default_frag.spv" "$SHADER_DIR/fxaa_vert.spv" "$SHADER_DIR/fxaa_frag.spv" "$SHADER_DIR/downsample_frag.spv" "$OUT_HEADER" <<'PYEOF'
import sys, os

def spv_to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines), len(data)

vert_path, frag_path, fxaa_vert_path, fxaa_frag_path, downsample_frag_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]

vert_hex, vert_size = spv_to_hex_lines(vert_path)
frag_hex, frag_size = spv_to_hex_lines(frag_path)
fxaa_vert_hex, fxaa_vert_size = spv_to_hex_lines(fxaa_vert_path)
fxaa_frag_hex, fxaa_frag_size = spv_to_hex_lines(fxaa_frag_path)
downsample_frag_hex, downsample_frag_size = spv_to_hex_lines(downsample_frag_path)

header = f"""#pragma once

// Auto-generated by build_vulkan_shaders.sh — do not edit.
// Rebuild with: ./build_vulkan_shaders.sh
//
// glslc is available at:
//   $ANDROID_NDK/shader-tools/darwin-x86_64/glslc   (macOS host)
//   $ANDROID_NDK/shader-tools/linux-x86_64/glslc    (Linux host)

namespace systems::leal::campello_renderer::shaders {{

static const unsigned char kDefaultVulkanVertShader[] = {{
{vert_hex}
}};
static const unsigned int kDefaultVulkanVertShaderSize = {vert_size};

static const unsigned char kDefaultVulkanFragShader[] = {{
{frag_hex}
}};
static const unsigned int kDefaultVulkanFragShaderSize = {frag_size};

static const unsigned char kDefaultVulkanFxaaVertShader[] = {{
{fxaa_vert_hex}
}};
static const unsigned int kDefaultVulkanFxaaVertShaderSize = {fxaa_vert_size};

static const unsigned char kDefaultVulkanFxaaFragShader[] = {{
{fxaa_frag_hex}
}};
static const unsigned int kDefaultVulkanFxaaFragShaderSize = {fxaa_frag_size};

static const unsigned char kDefaultVulkanDownsampleFragShader[] = {{
{downsample_frag_hex}
}};
static const unsigned int kDefaultVulkanDownsampleFragShaderSize = {downsample_frag_size};

}} // namespace systems::leal::campello_renderer::shaders
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}")
print(f"  vert: {vert_size} bytes")
print(f"  frag: {frag_size} bytes")
print(f"  fxaa_vert: {fxaa_vert_size} bytes")
print(f"  fxaa_frag: {fxaa_frag_size} bytes")
print(f"  downsample_frag: {downsample_frag_size} bytes")
PYEOF
