#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADER_DIR="$SCRIPT_DIR/shaders/metal"
OUT_HEADER="$SCRIPT_DIR/src/shaders/metal_default.h"

# ---------------------------------------------------------------------------
# Compile Metal → AIR → metallib for three SDK targets
# ---------------------------------------------------------------------------
echo "Compiling: default.metal → macOS"
xcrun -sdk macosx metal -c "$SHADER_DIR/default.metal" -o "$SHADER_DIR/default_macos.air"
xcrun -sdk macosx metallib "$SHADER_DIR/default_macos.air" -o "$SHADER_DIR/default_macos.metallib"

echo "Compiling: default.metal → iOS simulator"
xcrun -sdk iphonesimulator metal -c "$SHADER_DIR/default.metal" -o "$SHADER_DIR/default_iossim.air"
xcrun -sdk iphonesimulator metallib "$SHADER_DIR/default_iossim.air" -o "$SHADER_DIR/default_iossim.metallib"

echo "Compiling: default.metal → iOS device"
xcrun -sdk iphoneos metal -c "$SHADER_DIR/default.metal" -o "$SHADER_DIR/default_ios.air"
xcrun -sdk iphoneos metallib "$SHADER_DIR/default_ios.air" -o "$SHADER_DIR/default_ios.metallib"

# ---------------------------------------------------------------------------
# Generate combined header — platform selected at compile time via TARGET_OS_*
# ---------------------------------------------------------------------------
python3 - \
    "$SHADER_DIR/default_macos.metallib" \
    "$SHADER_DIR/default_iossim.metallib" \
    "$SHADER_DIR/default_ios.metallib" \
    "$OUT_HEADER" <<'PYEOF'
import sys

def to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

macos_path, iossim_path, ios_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

macos_hex,  macos_size  = to_hex_lines(macos_path)
iossim_hex, iossim_size = to_hex_lines(iossim_path)
ios_hex,    ios_size    = to_hex_lines(ios_path)

header = f"""#pragma once

// Auto-generated by build_metal_shaders.sh — do not edit.
// Rebuild with: ./build_metal_shaders.sh
//
// Three SDK variants are embedded and selected at compile time:
//   TARGET_OS_SIMULATOR  → iOS Simulator ({iossim_size} bytes)
//   TARGET_OS_IOS        → iOS device     ({ios_size} bytes)
//   else                 → macOS          ({macos_size} bytes)

#include <TargetConditionals.h>

namespace systems::leal::campello_renderer::shaders {{

#if TARGET_OS_SIMULATOR

static const unsigned char kDefaultMetalShader[] = {{
{iossim_hex}
}};
static const unsigned int kDefaultMetalShaderSize = {iossim_size};

#elif TARGET_OS_IOS

static const unsigned char kDefaultMetalShader[] = {{
{ios_hex}
}};
static const unsigned int kDefaultMetalShaderSize = {ios_size};

#else // macOS

static const unsigned char kDefaultMetalShader[] = {{
{macos_hex}
}};
static const unsigned int kDefaultMetalShaderSize = {macos_size};

#endif

}} // namespace systems::leal::campello_renderer::shaders
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}  (macOS {macos_size}B / iOS sim {iossim_size}B / iOS {ios_size}B)")
PYEOF

# Clean up intermediate files
rm -f "$SHADER_DIR"/*.air "$SHADER_DIR"/*.metallib
