#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_IMAGE="$SCRIPT_DIR/resources/environments/default_environment.hdr"
OUT_HEADER="$SCRIPT_DIR/src/environments/default_environment.h"

# ---------------------------------------------------------------------------
# Embed resources/environments/default_environment.hdr as a byte array header.
#
# Source: "Kiara 5 Noon" by Greg Zaal, https://polyhaven.com/a/kiara_5_noon
# License: CC0 1.0 (public domain, no attribution required).
# 1k (1024x512) Radiance HDR — real (non-tonemapped) linear radiance data, so
# sky/sun highlights exceed 1.0 and reflective/metallic/iridescent materials
# get real specular punch instead of being capped by an LDR source image.
# ---------------------------------------------------------------------------
python3 - "$SRC_IMAGE" "$OUT_HEADER" <<'PYEOF'
import sys

def to_hex_lines(path):
    data = open(path, "rb").read()
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines), len(data)

src_path, out_path = sys.argv[1], sys.argv[2]
hex_data, size = to_hex_lines(src_path)

header = f"""#pragma once

// Auto-generated by build_default_environment.sh — do not edit.
// Rebuild with: ./build_default_environment.sh
//
// Embedded source: resources/environments/default_environment.hdr
// "Kiara 5 Noon" by Greg Zaal (https://polyhaven.com/a/kiara_5_noon), CC0 1.0.
// 1024x512 equirectangular Radiance HDR ({size} bytes) — real linear
// radiance data (sky/sun exceed 1.0), used as the built-in default IBL
// environment map when the caller hasn't set one.

namespace systems::leal::campello_renderer::environments {{

static const unsigned char kDefaultEnvironmentHdr[] = {{
{hex_data}
}};
static const unsigned int kDefaultEnvironmentHdrSize = {size};

}} // namespace systems::leal::campello_renderer::environments
"""

open(out_path, "w").write(header)
print(f"Written: {out_path}  ({size} bytes embedded)")
PYEOF
