#Requires -Version 5.1
<#
Compiles shaders/directx/default.hlsl to DXIL and regenerates
src/shaders/directx_default.h — the DirectX analogue of
build_vulkan_shaders.sh / build_metal_shaders.sh.

Usage (from repo root, in PowerShell):
    ./build_directx_shaders.ps1

Requires dxc.exe (DirectX Shader Compiler) — ships with the Windows SDK at
  C:\Program Files (x86)\Windows Kits\10\bin\<version>\x64\dxc.exe
or via `winget install Microsoft.DirectXShaderCompiler` / the standalone
DXC release. This script searches the Windows SDK's Bin directory (newest
version first) before falling back to PATH. Header generation is pure
PowerShell (no Python dependency) so this script has no other prerequisites.
#>

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ShaderDir = Join-Path $ScriptDir "shaders\directx"
$OutHeader = Join-Path $ScriptDir "src\shaders\directx_default.h"
$HlslPath  = Join-Path $ShaderDir "default.hlsl"

# ---------------------------------------------------------------------------
# Locate dxc.exe — newest Windows Kits SDK version first, then PATH.
# ---------------------------------------------------------------------------
function Find-Dxc {
    $sdkBinRoot = "C:\Program Files (x86)\Windows Kits\10\bin"
    if (Test-Path $sdkBinRoot) {
        $candidate = Get-ChildItem $sdkBinRoot -Directory -ErrorAction SilentlyContinue |
            Sort-Object Name -Descending |
            ForEach-Object { Join-Path $_.FullName "x64\dxc.exe" } |
            Where-Object { Test-Path $_ } |
            Select-Object -First 1
        if ($candidate) { return $candidate }
    }
    $onPath = Get-Command dxc.exe -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    throw "dxc.exe not found. Install the Windows SDK (provides DirectX Shader Compiler) or the standalone DXC release, or add dxc.exe to PATH."
}

$Dxc = Find-Dxc
Write-Host "Using dxc: $Dxc"

# ---------------------------------------------------------------------------
# Compile HLSL -> DXIL, one invocation per entry point (dxc only accepts one
# -E/-T pair per run; each pulls only the globals that entry point actually
# references from the shared default.hlsl file — see that file's header
# comment on why entry points can safely reuse register numbers across
# unrelated pipelines).
# ---------------------------------------------------------------------------
$Entries = @(
    @{ Name = "default_vs";      Profile = "vs_6_0"; Entry = "vertexMain";           CArray = "kDefaultDirectXVertShader" },
    @{ Name = "default_ps";      Profile = "ps_6_0"; Entry = "pixelMain";             CArray = "kDefaultDirectXPixelShader" },
    @{ Name = "fxaa_vs";         Profile = "vs_6_0"; Entry = "fxaaVertex";            CArray = "kDefaultDirectXFxaaVertShader" },
    @{ Name = "fxaa_ps";         Profile = "ps_6_0"; Entry = "fxaaPixel";             CArray = "kDefaultDirectXFxaaPixelShader" },
    @{ Name = "downsample_ps";   Profile = "ps_6_0"; Entry = "downsamplePixel";       CArray = "kDefaultDirectXDownsamplePixelShader" },
    @{ Name = "skybox_ps";       Profile = "ps_6_0"; Entry = "skyboxPixel";           CArray = "kDefaultDirectXSkyboxPixelShader" },
    @{ Name = "iblbake_ps";      Profile = "ps_6_0"; Entry = "iblBakePixel";          CArray = "kDefaultDirectXIblBakePixelShader" },
    @{ Name = "procedural_bake"; Profile = "cs_6_0"; Entry = "proceduralBakeKernel";  CArray = "kDefaultDirectXProceduralBakeShader" }
)

foreach ($e in $Entries) {
    $outPath = Join-Path $ShaderDir "$($e.Name).dxil"
    & $Dxc -T $e.Profile -E $e.Entry $HlslPath -Fo $outPath
    if ($LASTEXITCODE -ne 0) {
        throw "dxc failed compiling entry point '$($e.Entry)' ($($e.Profile))"
    }
    Write-Host "Compiled: $($e.Entry) ($($e.Profile)) -> $($e.Name).dxil"
    $e.OutPath = $outPath
}

# ---------------------------------------------------------------------------
# Generate src/shaders/directx_default.h — plain PowerShell, 12 bytes/line to
# match the formatting build_vulkan_shaders.sh/build_metal_shaders.sh use.
# ---------------------------------------------------------------------------
function ConvertTo-CByteArray {
    param([byte[]]$Bytes)
    $sb = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $Bytes.Length; $i += 12) {
        $chunk = $Bytes[$i..([Math]::Min($i + 11, $Bytes.Length - 1))]
        $hex = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
        [void]$sb.AppendLine("    $hex,")
    }
    return $sb.ToString()
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// Auto-generated by build_directx_shaders.ps1 -- do not edit.")
[void]$sb.AppendLine("// Rebuild with: ./build_directx_shaders.ps1")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// dxc.exe ships with the Windows SDK:")
[void]$sb.AppendLine("//   C:\Program Files (x86)\Windows Kits\10\bin\<version>\x64\dxc.exe")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace systems::leal::campello_renderer::shaders {")
[void]$sb.AppendLine("")

foreach ($e in $Entries) {
    $bytes = [System.IO.File]::ReadAllBytes($e.OutPath)
    [void]$sb.AppendLine("static const unsigned char $($e.CArray)[] = {")
    [void]$sb.Append((ConvertTo-CByteArray -Bytes $bytes))
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const unsigned int $($e.CArray)Size = $($bytes.Length);")
    [void]$sb.AppendLine("")
    Write-Host "  $($e.CArray): $($bytes.Length) bytes"
}

[void]$sb.AppendLine("} // namespace systems::leal::campello_renderer::shaders")

# UTF8 without BOM, matching the other generated shader headers.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutHeader, $sb.ToString(), $utf8NoBom)

Write-Host "Written: $OutHeader"
